[package]
name = "wm-rs"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
log = "0.4.14"
stderrlog = "0.5.1"
x11 = { version = "2.19.1", features = ["xlib"] }

[target.x86_64-unknown-linux-gnu.runner]
runner = "./runner.sh"
